blank_issues_enabled: false
contact_links:
  - name: DWSIM Discussions
    url: https://github.com/DanWBR/dwsim10/discussions
    about: Questions about using DWSIM, ideas, and help. This repository is for case submissions only.
  - name: FOSSEE DWSIM flowsheeting project
    url: https://dwsim.fossee.in/
    about: Another large collection of user-contributed DWSIM flowsheets.
